# Generated by Django 4.1.5 on 2023-02-23 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0002_contract_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_classes', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='college.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='college.agreement')),
            ],
        ),
    ]
