# Generated by Django 4.1.5 on 2023-02-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_agreement_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='students_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
