# Generated by Django 4.1.5 on 2023-02-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0004_agreement_students_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duration",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="duration",
            name="start_date",
            field=models.DateField(),
        ),
    ]
