# Generated by Django 4.1.5 on 2023-03-09 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_alter_duration_end_date_alter_duration_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duration', to='college.agreement'),
        ),
    ]
